#!/usr/bin/env bash

binary_file="firefractal.com"
build_command="go build"
file_extension_expression=\.go$

$build_command && ./$binary_file &

inotifywait --format "%f" -me close_write -q . | while read file
do
	if [[ ! "$file" =~ $file_extension_expression ]]; then continue; fi
	go build && killall $binary_file; echo "File modified: $file. Restarting server." && ./$binary_file &
done

unset binary_file